### ISSUE TITLE
编译（挖坟）遇到的两个小问题

### ISSUE THREAD

**Issue by morninghut** [Locietta/C_Class_Project1#1]
make编译时遇到两个小问题：
> src/calcio.c: In function 'vExpr_gets':
src/calcio.c:45:15: error: 'c' may be used uninitialized [-Werror=maybe-uninitialized]
   45 |     return (c == EOF && cs == s) ? NULL : s;

* 给c初始化后解决

> gcc -Wall -Werror -O2 -I"./include" -I"./include/ADT" -g3   -c -o src/error.o src/error.c
    8 | #include "./include/error.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

* 或许可以改为#include"../include/error.h"？

* 总之[ ﾟ∀ﾟ]bbb

**Comment by Locietta** [comment]
Fixed. 

这个东西是很久以前写的啦，那个时候热衷于用纯C的结构+宏来模拟C++的STL，所以stack/queue的实现会有那么点奇怪（
